src/Web/VianorKyustendil.Web/Areas/Administration/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace VianorKyustendil.Web.Areas.Administration.Controllers
{
    [Area("Administration")]
    public class ArticlesController : AdministrationBaseController
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Search(string username)
        {
            return this.Content(username);
        }
    }
}

src/Web/VianorKyustendil.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VianorKyustendil.Web</title>

    @*<environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
                  crossorigin="anonymous"
                  integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
        </environment>*@
    @*<link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/logo.css" />*@
    <link href="/css/styles.css" rel="stylesheet" />
</head>
<body>
    <header class="site-header">
        <div class="container">
            <nav>
                <ul>
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                    <li><a asp-area="Administration" asp-controller="Articles" asp-action="Index">Articles</a></li>
                </ul>
                <ul>
                    <li class="site-logo">
                        <a href="#">
                            <h1 class="logo-wrapper logo-text"> V<span class="i-letter-font">I</span>ANOR &nbsp;&nbsp; KYUSTENDIL</h1>
                        </a>
                    </li>
                </ul>
                <ul>
                    <partial name="_LoginPartial" />
                </ul>
            </nav>
        </div>
    </header>


    <div class="container">
        <partial name="_CookieConsentPartial" />
            @RenderBody()
    </div>


    <footer class="border-top">
        <div class="container">
            <section class="site-footer">
                <p>&copy; 2019 - VianorKyustendil.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></p>
            </section>     
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>